### PR TITLE
Spelling and phrasing fixes

### PR DESCRIPTION
**Pull request by XDelta**

### CODE REVIEW

**Comment by epicEaston197** [comment]
I don't think this is the right Repository xD

**Comment by JackTheFoxOtter** [comment]
> I don't think this is the right Repository xD

Huh? But the file is this Repository's README.md
What would be a better Repository for a PR than this one? o.O

**Comment by epicEaston197** [comment]
> > I don't think this is the right Repository xD
> 
> Huh? But the file is this Repository's README.md What would be a better Repository for a PR than this one? o.O

https://github.com/Yellow-Dog-Man/Locale

**Comment by JackTheFoxOtter** [comment]
> > > I don't think this is the right Repository xD
> > 
> > 
> > Huh? But the file is this Repository's README.md What would be a better Repository for a PR than this one? o.O
> 
> https://github.com/Yellow-Dog-Man/Locale

This is not a PR for the game's locale, this is a PR for this repository's readme file.

**Comment by epicEaston197** [comment]
> > > > I don't think this is the right Repository xD
> > > 
> > > 
> > > Huh? But the file is this Repository's README.md What would be a better Repository for a PR than this one? o.O
> > 
> > 
> > https://github.com/Yellow-Dog-Man/Locale
> 
> This is not a PR for the game's locale, this is a PR for this repository's rea

> > > > I don't think this is the right Repository xD
> > > 
> > > 
> > > Huh? But the file is this Repository's README.md What would be a better Repository for a PR than this one? o.O
> > 
> > 
> > https://github.com/Yellow-Dog-Man/Locale
> 
> This is not a PR for the game's locale, this is a PR for this repository's readme file.

Huh weird
got it

**Review by ProbablePrime — APPROVED** [review]

**Pull request merged**
